name: CI
on:
  pull_request:
  push:
    branches:
      master

jobs:
  beefore:
    name: Pre-test checks
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        task: ['docs', 'package']
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install tox
    - name: Run Pre-test check
      run: |
        tox -e ${{ matrix.task }}

